config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"
  resources :users do
    resources :likes
    member do
      get :following, :followers, :users_recipes
    end
    
    resource :relationships, only: [:create, :destroy]
    get :followings, on: :member
    get :followers, on: :member
  end
  resources :recipes do
    get :followings, on: :member
    resources :comments
    resource :likes, only: [:create, :destroy]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :recipe
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :recipe

  validates_uniqueness_of :recipe_id, scope: :user_id
end

app/models/recipe.rb
class Recipe < ApplicationRecord
    belongs_to :user
    attachment :image

    has_many :comments
    has_many :likes, dependent: :destroy

    with_options presence: true do
        validates :title
        validates :body
        validates :image
    end

end

app/models/relationship.rb
class Relationship < ApplicationRecord
    belongs_to :following, class_name: 'User'
    belongs_to :follower, class_name: 'User'
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :relationships, foreign_key: :following_id
  has_many :followings, through: :relationships, source: :follower

  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: :follower_id
  has_many :followers, through: :reverse_of_relationships, source: :following
  has_many :comments
  has_many :likes, dependent: :destroy


  has_many :recipes, dependent: :destroy

  def already_liked?(recipe)
    self.likes.exists?(recipe_id: recipe.id)
  end

  def is_followed_by?(user)
    reverse_of_relationships.find_by(following_id: user.id).present?
  end
  
  has_many :recipes, dependent: :destroy
  attachment :profile_image

  validates :username, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    private
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!

    def create
        @recipe = Recipe.find(params[:recipe_id])
        @comment = current_user.comments.new(comment_params)

        if @comment.save
            redirect_to [@recipe]
        else
            render 'recipe/show'
        end
    end

    def destroy
        comment =current_user.comments.find(params[:id])
        comment.destroy

        redirect_to [:recipe, { id: params[:recipe_id] }]
    end

    private

    def comment_params
        params.require(:comment).permit(:body).merge(recipe_id: params[:recipe_id])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    before_action :authenticate_user!, only: %i[create destroy]

    def index
        @recipes = Recipe.joins(:likes).where(likes: { user_id: params[:user_id] })
    end

    def create
        @like = current_user.likes.create(recipe_id: params[:recipe_id])
        redirect_back(fallback_location: root_path)
    end

    def destroy
        @recipe = Recipe.find(params[:recipe_id])
        @like = current_user.likes.find_by(recipe_id: @recipe.id)
        @like.destroy
        redirect_back(fallback_location: root_path)
    end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  def index
    @recipes = Recipe.all
  end

  def show
    @recipe = Recipe.find(params[:id])
    @comment = Comment.new
  end

  def new
    @recipe = Recipe.new
  end

  def followings
    @users = Recipe.where(user_id: [current_user.id, *current_user.following_ids])
  end


  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user_id = current_user.id
    if @recipe.save
        redirect_to recipe_path(@recipe), notice: '投稿に成功しました。'
    else
        render :new
    end
  end

  def edit
    @recipe = Recipe.find(params[:id])
    if @recipe.user != current_user
      redirect_to recipes_path, alert: '不正なアクセスです。'
    end
  end

  def update
    @recipe = Recipe.find(params[:id])
    if @recipe.update(recipe_params)
      redirect_to recipe_path(@recipe), notice: 'レシピ情報を更新しました。'
    else
      render :edit
    end
  end

  def destroy
    recipe = Recipe.find(params[:id])
    recipe.destroy
    redirect_to recipes_path
  end

  private
  def recipe_params
    params.require(:recipe).permit(:title, :body, :image)
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
    before_action :authenticate_user!
    def create
        following = current_user.relationships.build(follower_id: params[:user_id])
        following.save
        redirect_to request.referrer || root_path
    end

    def destroy
        following = current_user.relationships.find_by(follower_id: params[:user_id])
        following.destroy
        redirect_to request.referrer || root_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  def index
    @users = User.all
  end
  def show
    @user = User.find(params[:id])
    @racipes = @user.recipes
  end
  def edit
    @user = User.find(params[:id])
    if @user != current_user
        redirect_to user_path(current_user), alert: "不正なアクセスです。"
    end
  end
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "ユーザー情報を更新しました。"
    else
      render :edit
    end
  end
  def followings
    user = User.find(params[:id])
    @users = user.followings
  end
  def followers
    user = User.find(params[:id])
    @users = user.followers
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :profile, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/relationship_helper.rb
module RelationshipHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<section class="section main-image" >
  <article class="media">
    <div class="media-content">
      <div class="content has-text-centered">
        <p>
          <strong class="is-size-1" style="font-family: cursive; color: #F4A460 ">recette</strong>
        </p>
      </div>
      <div class="columns is-centered">
        <div class="column is-5" style="margin: 2rem">
          <br>
          <%= link_to "ログイン", new_user_session_path, class: "button is-warning is-fullwidth" %>
          <br>
          <%= link_to "新規登録", new_user_registration_path, class: "button is-warning is-fullwidth" %>
        </div>
      </div>
    </div>
  </article>
</section>

app/views/likes/index.html.erb
<section class="section" style="margin-bottom: 66px">
  <div class="container">
    <div class="columns is-multiline">
      <% @recipes.each do |recipe| %>
        <div class="column is-4">
          <div class="card">
            <div class="card-image">
              <figure class="flame image is-4by5">
                <%= link_to recipe_path(recipe) do %>
                  <%= attachment_image_tag recipe, :image %>
                <% end %>
              </figure>
            </div>

          <div class="column">
            <table class="table is-fullwidth">
              <tr class="flame item">
                <td class="image is-64x64 style="border: none;">
                  <%= attachment_image_tag recipe.user, :profile_image, fallback: "no-image.png", class: "profile_image" %>
                </td>
              <td style="border: none;">
                  <%=link_to recipe.user.username, user_path(recipe.user) %>
                </td>
              <td style="margin-left: auto; margin-right: auto; border: none;">
                  <% if current_user.already_liked?(recipe) %>
                    <%= link_to recipe_likes_path(recipe), method: :delete do %>
                      <i class="fas fa-heart"></i>
                    <% end %>
                  <% else %>
                    <%= link_to recipe_likes_path(recipe), method: :post do %>
                      <i class="far fa-heart"></i>
                    <% end %>
                  <% end %>
                  <%= recipe.likes.count %>
              </td>
            </table>

            <div class="content">
              <time><%= recipe.updated_at.strftime("%Y-%m-%d ") %></time>
            </div>
          </div>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</section>

app/views/recipes/edit.html.erb
<% if @recipe.errors.any? %>
  <div class="notification is-danger">
    <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this object from being saved: not successfully</h2>
    <ul>
      <% @recipe.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<section class="section" style="margin-bottom: 66px">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6" style="padding: 0.75rem">
        <%= form_for @recipe do |f| %>
          <div class="field">
            <%= f.label :title, "レシピ名", class: "label" %>
            <%= f.text_field :title, class: "input" %>
          </div>

          <div class="field">
            <%= f.label :body, "作り方", class: "label" %>
            <%= f.text_area :body, class: "textarea" %>
          </div>

          <div class="field">
            <%= f.label :image, "写真", class: "label" %>
            <%= f.attachment_field :image, class: "input" %>
          </div>

          <%= f.submit '投稿', class: "button is-success" %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/recipes/followings.html.erb
<section class="section" style="margin-bottom: 66px">
  <div class="container">
    <div class="columns is-multiline">
      <% @users.each do |recipe| %>
        <div class="column is-4">
          <div class="card">
            <div class="card-image">
              <figure class="flame image is-4by5">
                <%= link_to recipe_path(recipe) do %>
                  <%= attachment_image_tag recipe, :image %>
                <% end %>
              </figure>
            </div>

          <div class="column">
            <table class="table is-fullwidth">
              <tr class="flame item">
                <td class="image is-64x64 style="border: none;">
                  <%= attachment_image_tag recipe.user, :profile_image, fallback: "no-image.png", class: "profile_image" %>
                </td>
              <td style="border: none;">
                  <%=link_to recipe.user.username, user_path(recipe.user) %>
                </td>
              <td style="margin-left: auto; margin-right: auto; border: none;">
                  <% if current_user.already_liked?(recipe) %>
                    <%= link_to recipe_likes_path(recipe), method: :delete do %>
                      <i class="fas fa-heart"></i>
                    <% end %>
                  <% else %>
                    <%= link_to recipe_likes_path(recipe), method: :post do %>
                      <i class="far fa-heart"></i>
                    <% end %>
                  <% end %>
                  <%= recipe.likes.count %>
              </td>
            </table>

            <div class="content" >
              <time><%= recipe.updated_at.strftime("%Y-%m-%d ") %></time>
            </div>
          </div>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</section>

app/views/recipes/index.html.erb
<section class="section" style="margin-bottom: 66px">
  <div class="container">
    <div class="columns is-multiline">
      <% @recipes.each do |recipe| %>
        <div class="column is-4">
          <div class="card">
            <div class="card-image">
              <figure class="flame image is-4by5">
                <%= link_to recipe_path(recipe) do %>
                  <%= attachment_image_tag recipe, :image %>
                <% end %>
              </figure>
            </div> 
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/recipes/new.html.erb
<% if @recipe.errors.any? %>
  <div class="notification is-danger">
    <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this object from being saved: not successfully</h2>
    <ul>
      <% @recipe.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<section class="section main-image" style="margin-bottom: 66px">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6" style="padding: 0.75rem">
        <%= form_for @recipe do |f| %>
          <div class="field">
            <%= f.label :title, "レシピ名", class: "label" %>
            <%= f.text_field :title, class: "input" %>
          </div>

          <div class="field">
            <%= f.label :body, "作り方", class: "label" %>
            <%= f.text_area :body, class: "textarea" %>
          </div>

          <div class="field">
            <%= f.label :image, "写真", class: "label" %>
            <div class="has-text-centered">
            <%= f.attachment_field :image, class: "input" %>
            </div>
          </div>

          <%= f.submit '投稿', class: "button is-success input mt-6" %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/recipes/show.html.erb
<section class="section" style="margin-bottom: 66px">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-5">
        <div class="card">
          <div class="card-image">
            <figure class="flame image is-4by5">
              <%= attachment_image_tag @recipe, :image %>
            </figure>
          </div>
          <div class="card-content">
            <div class="media">
              <div class="media-content">
                <p class="title is-4 has-text-centered"><%= @recipe.title %></p>
              </div>
            </div>
            <div class="content">
              <table class="table is-narrow">
                <tr>
                  <th>レシピ</th>
                </tr>
                <tr>
                  <td><%= simple_format @recipe.body %></td>
                </tr>
              </table>
              <% if @recipe.user.id == current_user.id %>
                <%= link_to "編集画面へ", edit_recipe_path(@recipe), class: "button is-success" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>

     

      <div class="column is-4">
        <article class="panel is-link">
          <p class="panel-heading">
             <%= @recipe.user.username %>
          </p>
          <div class="panel-block">
            <p class="control">
              <%= @recipe.user.profile %>
            </p>
          </div>
          <%= link_to user_path(@recipe.user), class: "panel-block" do %>
            <span class="panel-icon">
              <i class="fas fa-user" aria-hidden="true"></i>
            </span>
            <%= @recipe.user.username %> さんのページへ
          <% end %>
          
          <div>
          <table class="table is-fullwidth">
            <% @recipe.comments.each do |comment| %>
              <tr class="flame item">
              <td class="title is-size-6" style="margin: 0; margin-right: auto;">
                <%= link_to comment.user.username, [comment.user] %>
              </td>
              <td class="title is-size-6" style="margin: 0; margin-right: auto;">
                <%= comment.body %>
              </td>
              <td class="title is-size-6">
              <% if comment.user == current_user %>
                <%= link_to '削除', [@recipe, comment], method: :delete, class:"button is-small is-primary"%>
              <% end %>
              </td>
              </tr>
            <% end %>
          </table>
          </div>

          <div>
          <table class="table is-fullwidth">
          <tr class="flame item">
          <% if user_signed_in? %>
            <%= form_with model: [@recipe, @comment], local: true do |f| %>
              <td class="panel-block">
                <%= f.text_field :body %>
              </td>
              <td class="panel-block">
                <%= f.submit '投稿する'%>
              </td>
            <% end %>
          <% end %>
          </table>
          </div>

          <div class="panel-block">
            <% if current_user.already_liked?(@recipe) %>
              <%= link_to recipe_likes_path(@recipe), method: :delete do %>
                <i class="fas fa-heart"></i>
              <% end %>
              <% else %>
              <%= link_to recipe_likes_path(@recipe), method: :create do %>
                <i class="far fa-heart"></i>
              <% end %>
            <% end %>
            <%= @recipe.likes.count %>
          </div>
        </article>
      </div>
    </div>
  </div>
</section>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <div class="notification is-danger">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this object from being saved: not successfully</h2>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<section class="section" style="margin-bottom: 66px">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6" style="margin: 2rem">
        <%= form_for @user do |f| %>
          <div class="field">
            <%= f.label :username, "ユーザー名", class: "label" %>
            <%= f.text_field :username, class: "input" %>
          </div>

          <div class="field">
            <%= f.label :email, "メールアドレス", class: "label" %>
            <%= f.email_field :email, class: "input" %>
          </div>

          <div class="field">
            <%= f.label :profile, "プロフィール", class: "label" %>
            <%= f.text_area :profile, class: "textarea" %>
          </div>

          <div class="field">
            <%= f.label :profile_image, "プロフィール画像", class: "label" %>
            <%= f.attachment_field :profile_image, class: "input" %>
          </div>

          <%= f.submit "更新", class: "button is-success" %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/users/followers.html.erb
<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-8">
        <div class="columns is-centered">

         <div class="column is-8">
           <div>
           </div>

            <div>
              <table class="table is-fullwidth">
                <% @users.each do |user| %>
                  <tr class="flame item">
                  <td class="image is-128x128"  style="border: none;">
                  <%= attachment_image_tag user, :profile_image, fallback: "no-image.png", class: "profile_image is-rounded" %>
                 </td>
     
                     <td class="title is-size-6" style="margin-right: auto; margin-bottom: 0 ; border: none;"><%=link_to user.username, user_path(user) %>
                     </td>
                    <td style="margin-left: auto; margin-right: auto; border: none;">
                        <% if user != current_user %>
                            <% if user.is_followed_by?(current_user) %>
                                <%=link_to user_relationships_path(user), method: :delete do %>
                                    <button type="button" class="btn btn btn-danger">フォロー解除</button>
                                <% end %>
                                <% else %>
                                <%=link_to user_relationships_path(user), method: :post do %>
                                    <button type="button" class="btn btn btn-primary">フォロー</button>
                                <% end %>
                            <% end %>
                        <% end %>
                    </td>
                    </tr>

                <% end %>
              </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
        
        
        

app/views/users/followings.html.erb
<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-8">
        <div class="columns is-centered">

         <div class="column is-8">
           <div>
           </div>

            <div>
              <table class="table is-fullwidth">
                <% @users.each do |user| %>
                  <tr class="flame item">
                  <td class="image is-128x128"  style="border: none;">
                  <%= attachment_image_tag user, :profile_image, fallback: "no-image.png", class: "profile_image is-rounded" %>
                 </td>
     
                     <td class="title is-size-6" style="margin-right: auto; margin-bottom: 0 ; border: none;"><%=link_to user.username, user_path(user) %>
                     </td>
                    <td style="margin-left: auto; margin-right: auto; border: none;">
                        <% if user != current_user %>
                            <% if user.is_followed_by?(current_user) %>
                                <%=link_to user_relationships_path(user), method: :delete do %>
                                    <button type="button" class="btn btn btn-danger">フォロー解除</button>
                                <% end %>
                                <% else %>
                                <%=link_to user_relationships_path(user), method: :post do %>
                                    <button type="button" class="btn btn btn-primary">フォロー</button>
                                <% end %>
                            <% end %>
                        <% end %>
                    </td>
                    </tr>

                <% end %>
              </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
        
        
        

app/views/users/index.html.erb
<section class="section" style="margin-bottom: 66px">
  <div class="container">
    <div class="columns is-multiline">
      <% @users.each do |user| %>
        <div class="column is-3">
          <div class="card">
            <div class="card-content">
              <div class="card-image">
                <figure class="flame image is-128x128">
                  <%= link_to user_path(user) do %>
                    <%= attachment_image_tag user, :profile_image, fallback: "no-image.png" %>
                  <% end %>
                </figure>
              </div>
            </div>
            <div class="card-content">
              <div class="media">
                <div class="media-content">
                  <div class="title has-text-centered"><%=link_to user.username, user_path(user) %></div>
                </div>
              </div>
              <div class="content">
                投稿数：<%= user.recipes.count %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/users/show.html.erb
<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-8">
        <div class="columns is-centered">
          <div class="column is-4" style="margin: 2rem">
            <figure class=" flame image is-128x128"  style="margin-left: auto; margin-right: auto;">
              <%= attachment_image_tag @user, :profile_image, fallback: "no-image.png", class: "profile_image is-rounded" %>
            </figure>
          </div>
          <div class="column is-8 has-text-centered">
            <table class="table is-fullwidth">
              <tr style="text-align:center">
                <td class="is-size-4" >
                  <strong><%= @user.username %></strong>
                </td>
                <p class="text-small"><%= link_to @user.followings.count, followings_user_path(@user) %> フォロー <%= link_to @user.followers.count, followers_user_path(@user) %>フォロワー</p>
                <div>
                  <%= link_to "いいね一覧", [@user, :likes] %>
                </div>

                <% if @user.id == current_user.id %>
                <tb class="is-size-4">
                <%= @user.email %>
                </tb>

                <td >
                    <%= link_to "編集", edit_user_path(@user), class: "button is-primary" %>
                </td>
                <td>
                    <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "button is-primary" %>
                </td>
                <div>
                  <% else %>
                    <% if @user.is_followed_by?(current_user) %>
                      <%= link_to user_relationships_path(@user),  method: :delete do %>
                        <button class="button is-primary">フォロー解除</button>
                      <% end %>
                    <% else %>
                      <%= link_to user_relationships_path(@user),  method: :post do %>
                        <button class="button is-primary">フォロー</button>
                      <% end %>
                    <% end %>
                  <% end %>
                </div>
              </tr>
            <table class="table is-fullwidth">
              <tr>
                <td>
                  <%= @user.profile %>
                </td>
              </tr>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="section" style="margin-bottom: 66px">
  <div class="container">
    <div class="columns is-multiline">
      <% @user.recipes.each do |recipe| %>
        <div class="column is-4">
          <div class="card">
            <div class="card-image">
              <figure class="image is-4by5">
                <%= link_to recipe_path(recipe) do %>
                  <%= attachment_image_tag recipe, :image, fallback: "no-image.png" %>
                <% end %>
              </figure>
            </div>
            <div class="card-content">
              <div class="media">
                <div class="media-content">
                  <%= link_to recipe_path(recipe), class: "panel-block" do %>
                    <span class="panel-icon">
                      <i class="fas fa-book" aria-hidden="true"></i>
                    </span>
                    このレシピを見る
                  <% end %>
                  <% if @user.id == current_user.id %>
                    <%= link_to edit_recipe_path(recipe), class: "panel-block" do %>
                      <span class="panel-icon">
                        <i class="fas fa-edit"></i>
                      </span>
                      このレシピを編集する
                    <% end %>
                    <%= link_to recipe_path(recipe), method: :delete, data: {confirm: "削除しますか？"}, class: "panel-block" do %>
                      <span class="panel-icon">
                        <i class="fas fa-trash"></i>
                      </span>
                      このレシピを削除する
                    <% end %>
                  <% end %>
                </div>
              </div>
              <div class="content">
                <time><%= recipe.updated_at.strftime("%Y-%m-%d ") %></time>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>