config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"
  resources :users do
    resources :likes
    member do
      get :following, :followers, :users_recipes
    end
    
    resource :relationships, only: [:create, :destroy]
    get :followings, on: :member
    get :followers, on: :member
  end
  resources :recipes do
    get :followings, on: :member
    resources :comments
    resource :likes, only: [:create, :destroy]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :recipe
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :recipe

  validates_uniqueness_of :recipe_id, scope: :user_id
end

app/models/recipe.rb
class Recipe < ApplicationRecord
    belongs_to :user
    attachment :image

    has_many :comments
    has_many :likes, dependent: :destroy

    with_options presence: true do
        validates :title
        validates :body
        validates :image
    end

end

app/models/relationship.rb
class Relationship < ApplicationRecord
    belongs_to :following, class_name: 'User'
    belongs_to :follower, class_name: 'User'
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :relationships, foreign_key: :following_id
  has_many :followings, through: :relationships, source: :follower

  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: :follower_id
  has_many :followers, through: :reverse_of_relationships, source: :following
  has_many :comments
  has_many :likes, dependent: :destroy


  has_many :recipes, dependent: :destroy

  def already_liked?(recipe)
    self.likes.exists?(recipe_id: recipe.id)
  end

  def is_followed_by?(user)
    reverse_of_relationships.find_by(following_id: user.id).present?
  end
  
  has_many :recipes, dependent: :destroy
  attachment :profile_image

  validates :username, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    private
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!

    def create
        @recipe = Recipe.find(params[:recipe_id])
        @comment = current_user.comments.new(comment_params)

        if @comment.save
            redirect_to [@recipe]
        else
            render 'recipe/show'
        end
    end

    def destroy
        comment =current_user.comments.find(params[:id])
        comment.destroy

        redirect_to [:recipe, { id: params[:recipe_id] }]
    end

    private

    def comment_params
        params.require(:comment).permit(:body).merge(recipe_id: params[:recipe_id])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    before_action :authenticate_user!, only: %i[create destroy]

    def index
        @recipes = Recipe.joins(:likes).where(likes: { user_id: params[:user_id] })
    end

    def create
        @like = current_user.likes.create(recipe_id: params[:recipe_id])
        redirect_back(fallback_location: root_path)
    end

    def destroy
        @recipe = Recipe.find(params[:recipe_id])
        @like = current_user.likes.find_by(recipe_id: @recipe.id)
        @like.destroy
        redirect_back(fallback_location: root_path)
    end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  def index
    @recipes = Recipe.all
  end

  def show
    @recipe = Recipe.find(params[:id])
    @comment = Comment.new
  end

  def new
    @recipe = Recipe.new
  end

  def followings
    @users = Recipe.where(user_id: [current_user.id, *current_user.following_ids])
  end


  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user_id = current_user.id
    if @recipe.save
        redirect_to recipe_path(@recipe), notice: '投稿に成功しました。'
    else
        render :new
    end
  end

  def edit
    @recipe = Recipe.find(params[:id])
    if @recipe.user != current_user
      redirect_to recipes_path, alert: '不正なアクセスです。'
    end
  end

  def update
    @recipe = Recipe.find(params[:id])
    if @recipe.update(recipe_params)
      redirect_to recipe_path(@recipe), notice: 'レシピ情報を更新しました。'
    else
      render :edit
    end
  end

  def destroy
    recipe = Recipe.find(params[:id])
    recipe.destroy
    redirect_to recipes_path
  end

  private
  def recipe_params
    params.require(:recipe).permit(:title, :body, :image)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  def index
    @users = User.all
  end
  def show
    @user = User.find(params[:id])
    @racipes = @user.recipes
  end
  def edit
    @user = User.find(params[:id])
    if @user != current_user
        redirect_to user_path(current_user), alert: "不正なアクセスです。"
    end
  end
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "ユーザー情報を更新しました。"
    else
      render :edit
    end
  end
  def followings
    user = User.find(params[:id])
    @users = user.followings
  end
  def followers
    user = User.find(params[:id])
    @users = user.followers
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :profile, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/relationship_helper.rb
module RelationshipHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Recette</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.min.css" integrity="sha256-UzFD2WYH2U1dQpKDjjZK72VtPeWP50NoJjd26rnAdUI=" crossorigin="anonymous" />
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style="margin-bottom: 66px">
    <% if flash[:notice] %>
      <div class="notification is-info">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="notification is-danger">
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>

    <nav style="border-bottom: groove">
      <div class="navbar-brand">
        <%= link_to root_path, class: "navbar-item" do %>
          <h1 class="title is-4 " style="font-family: cursive; color: #F4A460;">recette</h1>

        <% end %>
        
      <% if user_signed_in? %>
        <div id="navbarExampleTransparentExample" class="navbar-menu">
          <div class="navbar-item">
            <%= link_to "レシピ一覧", recipes_path, class: "navbar-item button is-warning is-light" %>
          </div>
          <div class="navbar-item">
            <%= link_to "レシピ投稿", new_recipe_path, class: "navbar-item button is-warning is-light" %>
          </div>
          <div class="navbar-item">
            <%= link_to "タイムライン", followings_recipe_path(:id), class: "navbar-item button is-warning is-light" %>
          </div>





          <div class="navbar-end">
            <div class="navbar-item">
              <div class="field is-grouped">
                <p class="control">
                  <%= link_to "ユーザー一覧", users_path, class: " button is-warning is-light" %>
                </p>
                <p class="control">
                  <%= link_to "マイページ", user_path(current_user), class: "button is-warning is-light" %>
                </p>
                <p class="control">
                  <%= link_to "お気に入り一覧", user_likes_path(current_user), class: "button is-warning is-light" %>
                </p>
              </div>
            </div>
          </div>
        </div>
      <% else %>
        <div id="navbarExampleTransparentExample" class="navbar-menu">
          <div class="navbar-item">
            <%= link_to "レシピ一覧", recipes_path, class: "navbar-item button is-warning is-light" %>
          </div>
          <div class="navbar-item">
            <%= link_to "ユーザー一覧", users_path, class: "navbar-item button is-warning is-light" %>
          </div>
          <div class="navbar-item">
          <%= link_to "タイムライン", followings_recipe_path(:id), class: "navbar-item button is-warning is-light" %>
        </div>

          <div class="navbar-end">
            <div class="navbar-item">
              <div class="field is-grouped">
                <p class="control">
                  <%= link_to "ログイン", new_user_session_path, class: "button is-warning is-light" %>
                </p>
                <p class="control">
                  <%= link_to "新規登録", new_user_registration_path, class: "button is-warning is-light" %>
                </p>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </nav>

  <aside >
    <nav class="navbar has-background-grey is-fixed-bottom navbar-brand columns is-mobile" role="navigation">
      <% if user_signed_in? %>
        <%= link_to followings_recipe_path(:id), class: "navbar-item column has-text-centered has-text-white" do %>
          <i class="fa fa-home"></i>
          <p class="is-size-7 has-text-centered">HOME</p>
        <% end %>
        <%= link_to recipes_path, class: "navbar-item column has-text-centered has-text-white" do %>
          <i class="fa fa-search"></i>
          <p class="is-size-7 has-text-centered">Search</p>
        <% end %>
        <%= link_to new_recipe_path, class: "navbar-item column has-text-centered has-text-white" do %>
          <i class="far fa-plus-square"></i>
          <p class="is-size-7 has-text-centered">NEW</p>
        <% end %>
        <%= link_to  user_path(current_user), class: "navbar-item column has-text-centered has-text-white" do %>
          <i class="fa fa-user"></i>
          <p class="is-size-7 has-text-centered">Account</p>
        <% end %>
        <%= link_to user_likes_path(current_user), class: "navbar-item column has-text-centered has-text-white" do %>
          <i class="far fa-heart"></i>
          <p class="is-size-7 has-text-centered has-text-white">Favorite</p>
        <% end %>

      <% else %>
      <nav class="navbar has-background-grey is-fixed-bottom navbar-brand columns is-mobile" role="navigation">
      <%= link_to recipes_path, class: "navbar-item column has-text-centered has-text-white" do %>
              <i class="fa fa-home"></i>
              <p class="is-size-7 has-text-centered has-text-white">HOME</p>
            <% end %>
            <%= link_to users_path, class: "navbar-item column has-text-centered has-text-white" do %>
              <i class="fa fa-user"></i>
              <p class="is-size-7 has-text-centered has-text-white">Account</p>
            <% end %>
            <%= link_to new_user_session_path, class: "navbar-item column has-text-centered has-text-white" do %>
              <i class="fas fa-sign-in-alt"></i>
              <p class="is-size-7 has-text-centered has-text-white">LOGIN</p>
            <% end %>
            <%= link_to new_user_registration_path, class: "navbar-item column has-text-centered has-text-white" do %>
              <i class="fa fa-user"></i>
              <p class="is-size-7 has-text-centered has-text-white">NEW</p>
            <% end %>
      <% end %>
    </nav>
  </aside>
    <%= yield %>
  </body>

</html>